-- MySQL Script generated by MySQL Workbench
-- Fri Jul 12 15:40:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(77) NOT NULL,
  `nome` VARCHAR(77) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `Administrador_id_administrador` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_Aluno_Administrador1_idx` (`Administrador_id_administrador` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Administrador1`
    FOREIGN KEY (`Administrador_id_administrador`)
    REFERENCES `mydb`.`Administrador` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrutor` (
  `id_instrutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(77) NOT NULL,
  `email` VARCHAR(77) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `Administrador_id_administrador` INT NOT NULL,
  PRIMARY KEY (`id_instrutor`),
  INDEX `fk_instrutor_Administrador1_idx` (`Administrador_id_administrador` ASC) VISIBLE,
  CONSTRAINT `fk_instrutor_Administrador1`
    FOREIGN KEY (`Administrador_id_administrador`)
    REFERENCES `mydb`.`Administrador` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlanoTreino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlanoTreino` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `nome plano` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `instrutor_id_instrutor` INT NOT NULL,
  `Aluno_id_aluno` INT NOT NULL,
  `Administrador_id_administrador` INT NOT NULL,
  PRIMARY KEY (`id_plano`),
  INDEX `fk_PlanoTreino_instrutor1_idx` (`instrutor_id_instrutor` ASC) VISIBLE,
  INDEX `fk_PlanoTreino_Aluno1_idx` (`Aluno_id_aluno` ASC) VISIBLE,
  INDEX `fk_PlanoTreino_Administrador1_idx` (`Administrador_id_administrador` ASC) VISIBLE,
  CONSTRAINT `fk_PlanoTreino_instrutor1`
    FOREIGN KEY (`instrutor_id_instrutor`)
    REFERENCES `mydb`.`instrutor` (`id_instrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlanoTreino_Aluno1`
    FOREIGN KEY (`Aluno_id_aluno`)
    REFERENCES `mydb`.`Aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlanoTreino_Administrador1`
    FOREIGN KEY (`Administrador_id_administrador`)
    REFERENCES `mydb`.`Administrador` (`id_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AtividadeFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AtividadeFisica` (
  `id_atividade` INT NOT NULL AUTO_INCREMENT,
  `tipo_exercicio` VARCHAR(45) NOT NULL,
  `duracao` INT NOT NULL,
  `intensidade` VARCHAR(45) NOT NULL,
  `Aluno_id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_atividade`),
  INDEX `fk_AtividadeFisica_Aluno_idx` (`Aluno_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_AtividadeFisica_Aluno`
    FOREIGN KEY (`Aluno_id_aluno`)
    REFERENCES `mydb`.`Aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- Verificar se o usuário já existe
SELECT user, host FROM mysql.user WHERE user = 'usuario_gym' AND host = 'localhost';

-- Se o usuário existir, você pode deletá-lo
DROP USER 'usuario_gym'@'localhost';

-- Agora, crie novamente o usuário
CREATE USER 'usuario_gym'@'localhost' IDENTIFIED BY 'senhaSegura';

-- Conceda as permissões necessárias
GRANT SELECT, INSERT, UPDATE ON mydb.* TO 'usuario_gym'@'localhost';

-- Aplicando as permissões
FLUSH PRIVILEGES;

-- Verificar se a view já existe
SHOW FULL TABLES IN mydb WHERE TABLE_TYPE = 'VIEW' AND Tables_in_mydb = 'planos_por_aluno';

-- Se a view existir, você pode deletá-la
DROP VIEW IF EXISTS planos_por_aluno;

-- Agora, crie novamente a view
CREATE VIEW planos_por_aluno AS
SELECT a.nome AS aluno, p.`nome plano`, p.descricao
FROM PlanoTreino p
JOIN Aluno a ON p.Aluno_id_aluno = a.id_aluno;


DELIMITER //

CREATE PROCEDURE registrar_atividade(
    IN p_tipo_exercicio VARCHAR(45),
    IN p_duracao INT,
    IN p_intensidade VARCHAR(45),
    IN p_aluno_id INT
)
BEGIN
    INSERT INTO AtividadeFisica (tipo_exercicio, duracao, intensidade, Aluno_id_aluno)
    VALUES (p_tipo_exercicio, p_duracao, p_intensidade, p_aluno_id);
END //

DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
